config/routes.rb
FunImages::Application.routes.draw do

  namespace :ajax do
    resources :hover_card, :only => :show
  end

  namespace :admin do
    root :to => 'welcome#index'
    resources :images do 
      resources :comments, :only => [:destroy, :edit]
    end
    resources :users, :only => [:index, :show, :edit, :update]
  end

  resources :images, :only => [] do
    resources :comments, :except => [:index, :show] do
      get 'i_like'
      get 'dont_like'
    end
  end

  namespace :my do
    resources :comments, :only => [:index]
    resources :account, :only => [:index] do
      collection do
        post 'change_nick'
      end
    end
    resources :statistics, :only => :index
  end
  match 'comments/i_like' => 'my/comments#i_like'

  # js
  match 'javascripts/js_translations' => 'js_translations#index'

  root :to => "welcome#index"

  match '/:shown_date' => 'welcome#index_with_date', :constraints => {:shown_date => /\d{4}-\d{2}-\d{2}/}

  devise_for :users, :controllers => {:omniauth_callbacks => 'authentications'} do
    root :to => 'welcome#index'
  end

  match '/:user_name' => 'user_public_page#index'
  match '/:user_name/:shown_date' => 'user_public_page#index_with_date', :constraints => {:shown_date => /\d{4}-\d{2}-\d{2}/}
end

app/controllers/my/account_controller.rb
class My::AccountController < ::UserController
  def index; end

  def change_nick
    if params.has_key? :account and params[:account].has_key? :nick
      current_user.nick = params[:account][:nick]
      current_user.validate_nick
      if current_user.errors.size == 0 and current_user.save
        redirect_to :back, :notice => t(:saved_successfully)
      else
        flash[:alert] = t :fix_errors
        render :index
      end
    else
      flash[:alert] = t :fix_errors
      render :index
    end
  end
end

app/controllers/my/comments_controller.rb
class My::CommentsController < ::UserController
  def index
  end

  def i_like
  end

end

app/controllers/my/statistics_controller.rb
class My::StatisticsController < ::UserController
  def index

  end
end

app/views/my/account/index.html.haml
.page
  %h1= t :'my.overview'

  .menu
    = render 'my/shared/menu'
  .content
    = form_tag change_nick_my_account_index_url, :method => :post do
      %p
        %label(for="user_nick")= t(:'my.account.nick') + ':'
        %br
        - if current_user.errors.any?
          #error_explanation
            %ul
              - current_user.errors.full_messages.each do |message|
                %li
                  = message
        %input#user_nick{:value => current_user.nick}(name="account[nick]")
      %input#account_submit{:value => t(:save)}(name="commit" type="submit")