config/routes.rb
FunImages::Application.routes.draw do

  namespace :ajax do
    resources :hover_card, :only => :show
  end

  namespace :admin do
    root :to => 'welcome#index'
    resources :images do 
      resources :comments, :only => [:destroy, :edit]
    end
    resources :users, :only => [:index, :show, :edit, :update]
  end

  resources :images, :only => [] do
    resources :comments, :except => [:index, :show] do
      get 'i_like'
      get 'dont_like'
    end
  end

  namespace :my do
    resources :comments, :only => [:index]
    resources :account, :only => [:index] do
      collection do
        post 'change_nick'
      end
    end
    resources :statistics, :only => :index
  end
  match 'comments/i_like' => 'my/comments#i_like'

  # js
  match 'javascripts/js_translations' => 'js_translations#index'

  root :to => "welcome#index"

  match '/:shown_date' => 'welcome#index_with_date', :constraints => {:shown_date => /\d{4}-\d{2}-\d{2}/}

  devise_for :users, :controllers => {:omniauth_callbacks => 'authentications'} do
    root :to => 'welcome#index'
  end

  match '/:user_name' => 'user_public_page#index'
  match '/:user_name/:shown_date' => 'user_public_page#index_with_date', :constraints => {:shown_date => /\d{4}-\d{2}-\d{2}/}
end

app/models/image.rb
require 'carrierwave/orm/mongoid'
class Image
  include Mongoid::Document
  include Mongoid::Timestamps

  field :is_checked, :type => Boolean, :default => false
  field :title, :type => String
  field :description, :type => String
  mount_uploader :image, ImageUploader
  field :shown_date, :type => Integer
  index :shown_date, :unique => true
  field :alt

  attr_accessible :title, :description, :image, :shown_date

  validates_presence_of :image
  validates_uniqueness_of :shown_date

  referenced_in :user
  references_many :comments

  class << self
    def find_closest_images image
      return [] unless image
      days_limit = 5
      if image.shown_date < Date.today

      else
        Image.desc(:shown_date).limit days_limit
      end
    end
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ::AdminController

  before_filter :convert_date_to_integer, :only => [:create, :update]

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
    @image = Image.find(params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
    render 'edit'
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  def create
    @image = Image.new(params[:image])
    @image.shown_date = @shown_date.to_i
    @image.user_id = current_user.id

    if @image.save
      redirect_to([:admin, @image], :notice => 'Image was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /images/1
  def update
    @image = Image.find(params[:id])
    if @image.update_attributes(params[:image].merge({:shown_date => @shown_date.to_i}))
      redirect_to([:admin, @image], :notice => 'Image was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /images/1
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to admin_images_url
  end

  private
  def convert_date_to_integer
    @shown_date = Date.parse "#{params[:shown_date][:year]}-#{params[:shown_date][:month]}-#{params[:shown_date][:day]}"
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_filter :authenticate_user!, :super_admin_level_access
  layout 'admin'

  # GET /images
  def index
    @images = Image.all
  end

  # GET /images/1
  def show
    @image = Image.find(params[:id])
  end

  # GET /images/new
  def new
    @image = Image.new
    render 'edit'
  end

  # GET /images/1/edit
  def edit
    @image = Image.find(params[:id])
  end

  # POST /images
  def create
    @image = Image.new(params[:image])
    @image.user_id = current_user.id

    if @image.save
      redirect_to(@image, :notice => 'Image was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /images/1
  def update
    @image = Image.find(params[:id])

    if @image.update_attributes(params[:image])
      redirect_to(@image, :notice => 'Image was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /images/1
  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    redirect_to images_url
  end
end

app/views/admin/images/edit.html.haml
- if @image.new_record?
  %h1 New image
- else
  %h1 Editing image

= form_for [:admin, @image], :html => {:multipart => true} do |f|
  -if @image.errors.any?
    #error_explanation
      %h2
        = pluralize @image.errors.count, "error"
        prohibited this image from being saved:
      %ul
        - @image.errors.full_messages.each do |msg|
          %li
            = msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :image
    = f.file_field :image
  .field
    = label_tag :shown_date
    = select_date(@image.shown_date.nil? ? Date.today : @image.shown_date.to_date, {:prefix => 'shown_date'}, {})

  .actions
    = f.submit

= link_to 'Show', [:admin, @image]
|
= link_to 'Back', admin_images_path

app/views/admin/images/index.html.haml
%h1
  Listing images

= link_to 'New image', new_admin_image_path

.images
- @images.each do |image|
  .image
    %h2
      = image.title
    %p
      = image.description
    = image_tag image.image.thumb.url
    .menu
      = link_to 'Show', admin_image_path(image)
      = link_to 'Edit', edit_admin_image_path(image)
      = link_to 'Destroy', [:admin, image], :confirm => 'Are u sure?', :method => :delete

app/views/admin/images/show.html.haml
%p#notice
  = notice

%p
  %b
    Title:
  = @image.title

%p
  %b
    Desctiption:
  = @image.title

= image_tag @image.image.url

.comments
  - @image.comments.each do |comment|
    .comment
      .author
        = comment.user_author.email
      .body
        = comment.body
      .links
        = link_to t(:edit), edit_admin_image_comment_path(@image, comment)
        = link_to t(:destroy_comment), [:admin, @image, comment], :confirm => 'Are u sure?', :method => :delete